; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Mic Test"
#define MyAppVersion "2.0.0.0"
#define MyAppPublisher "Sajeeb Chandan Saha"
#define MyAppExeName "Mic Test.exe"
#define MyAppPublisherURL "https://www.fiverr.com/sajeeb_chandan"
#define MyAppSupportURL "https://github.com/sajeebchandan/MicTest"
#define MyAppUpdatesURL "https://github.com/sajeebchandan/MicTest/releases/latest"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4313C9F2-8F07-4383-8169-C0F359758311}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppPublisherURL}
AppSupportURL={#MyAppSupportURL}
AppUpdatesURL={#MyAppUpdatesURL}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
DisableProgramGroupPage=yes
; The [Icons] "quicklaunchicon" entry uses {userappdata} but its [Tasks] entry has a proper IsAdminInstallMode Check.
UsedUserAreasWarning=no
InfoBeforeFile=F:\IDEs\Visual Studio 2019\Mic Test\Mic Test\Mic Test_install_before.txt
InfoAfterFile=F:\IDEs\Visual Studio 2019\Mic Test\Mic Test\Mic Test_install_after.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=F:\IDEs\Visual Studio 2019\Mic Test
OutputBaseFilename=Mic_Test_Setup
SetupIconFile=F:\IDEs\Visual Studio 2019\Mic Test\Mic Test\microphone__5__MjP_icon.ico
Compression=lzma/ultra64
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\{#MyAppExeName}
UninstallDisplayName={#MyAppName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 6.1; Check: not IsAdminInstallMode

[Files]
Source: "F:\IDEs\Visual Studio 2019\Mic Test\Mic Test\bin\Debug\Mic Test.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\IDEs\Visual Studio 2019\Mic Test\Mic Test\bin\Debug\CSCore.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\IDEs\Visual Studio 2019\Mic Test\Mic Test\bin\Debug\Mic Test.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\IDEs\Visual Studio 2019\Mic Test\Mic Test\bin\Debug\Mic Test.exe.config"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

